Adding config to code cov

diff --git a/.github/workflows/integration-tests.yml b/.github/workflows/integration-tests.yml
--- a/.github/workflows/integration-tests.yml
+++ b/.github/workflows/integration-tests.yml
@@ -8,7 +8,7 @@ on:
   workflow_dispatch:
 
 jobs:
-  build:
+  Test:
 
     runs-on: ubuntu-latest
 
@@ -20,11 +20,32 @@ jobs:
       with:
         dotnet-version: 5.0.x
     
-    - name: Restore dependencies
+    - name: Restore
       run: dotnet restore
     
     - name: Build
       run: dotnet build --no-restore
     
     - name: Test
-      run: dotnet test --no-build --verbosity normal
+      run: dotnet test --no-build --verbosity normal --logger "trx" --collect:"XPlat Code Coverage" --results-directory ./coverage
+
+    - name: Test Reporter
+      uses: dorny/test-reporter@v1.5.0
+      if: success() || failure()  
+      with:
+        name: Test report       # Name of the check run which will be created
+        path: '**/*.trx'        # Path to test results
+        reporter: dotnet-trx    # Format of test results
+        'fail-on-error': false   # Fail the workflow if the test results contain errors
+
+    - name: Coverage Reporter
+      uses: codecov/codecov-action@v2
+      if: success() || failure()  
+      with:
+        token: ${{ secrets.CODECOV_TOKEN }}
+        fail_ci_if_error: true
+        files: '**/coverage.cobertura.xml'
+        flags: unittests
+        name: codecov-umbrella
+        path_to_write_report: ./coverage/codecov_report.txt
+        verbose: true
