Adding type error not found (#1)
* Adding fuget reference in readme

* Simplifying tests of the notation CompareLessNumberIsValid

* Simplifying tests of the notation ComparePlusNumberIsValid

* Simplifying the integer test

* Simplifying the longer test

* Adding SourceLink to github

* Text corrections

* Simplifying the required test

* Simplifying the decimal test

* Update packages

* Remove test with double.MaxValue and double.MinValue

* Adding action to check build

* Adding config to code cov

* Adding config to sonar

* Add publish to github

* Git ignore folder coverage

* Adding type error not found

* Adding readme to nuget

* Update project to 0.11.0

diff --git a/.github/workflows/integration-tests.yml b/.github/workflows/integration-tests.yml
--- a/.github/workflows/integration-tests.yml
+++ b/.github/workflows/integration-tests.yml
@@ -8,8 +8,9 @@ on:
   workflow_dispatch:
 
 jobs:
-  build:
-
+  # Start test
+  Test:
+    name: Code-Coverage and Unit Tests
     runs-on: ubuntu-latest
 
     steps:
@@ -20,11 +21,80 @@ jobs:
       with:
         dotnet-version: 5.0.x
     
-    - name: Restore dependencies
+    - name: Restore
       run: dotnet restore
     
     - name: Build
       run: dotnet build --no-restore
     
     - name: Test
-      run: dotnet test --no-build --verbosity normal
+      run: dotnet test --no-build --verbosity normal --logger "trx" --collect:"XPlat Code Coverage" --results-directory ./coverage
+
+    - name: Test Reporter
+      uses: dorny/test-reporter@v1.5.0
+      if: success() || failure()  
+      with:
+        name: Test report       # Name of the check run which will be created
+        path: '**/*.trx'        # Path to test results
+        reporter: dotnet-trx    # Format of test results
+        'fail-on-error': false  # Fail the workflow if the test results contain errors
+
+    - name: Coverage Reporter
+      uses: codecov/codecov-action@v2
+      if: success() || failure()  
+      with:
+        token: ${{ secrets.CODECOV_TOKEN }}
+        fail_ci_if_error: true
+        files: '**/coverage.cobertura.xml'
+        flags: unittests
+        name: codecov-umbrella
+        path_to_write_report: ./coverage/codecov_report.txt
+        verbose: true
+  # end of Test
+  # Start analyze
+  analyze:
+    name: Sonar Cloud Analyze
+    runs-on: windows-latest
+    steps:
+      - name: Set up JDK 11
+        uses: actions/setup-java@v1
+        with:
+          java-version: 1.11
+      - uses: actions/checkout@v2
+        with:
+          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
+      
+      - name: Cache SonarCloud packages
+        uses: actions/cache@v1
+        with:
+          path: ~\sonar\cache
+          key: ${{ runner.os }}-sonar
+          restore-keys: ${{ runner.os }}-sonar
+      
+      - name: Cache SonarCloud scanner
+        id: cache-sonar-scanner
+        uses: actions/cache@v1
+        with:
+          path: .\.sonar\scanner
+          key: ${{ runner.os }}-sonar-scanner
+          restore-keys: ${{ runner.os }}-sonar-scanner
+      
+      - name: Install SonarCloud scanner
+        if: steps.cache-sonar-scanner.outputs.cache-hit != 'true'
+        shell: powershell
+        run: |
+          New-Item -Path .\.sonar\scanner -ItemType Directory
+          dotnet tool update dotnet-sonarscanner --tool-path .\.sonar\scanner
+      
+      - name: Build and analyze
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
+          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+        shell: powershell
+        run: |
+          .\.sonar\scanner\dotnet-sonarscanner begin /k:"RenatoPacheco_IntegracaoContinua.Csharp" /o:"renatopacheco" /d:sonar.login="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.cs.opencover.reportsPaths="test\coverage.opencover.xml" /d:sonar.cs.vstest.reportsPaths="test\TestResults\report.trx"
+          dotnet restore
+          dotnet build --configuration Release --no-restore
+          dotnet test -l "trx;LogFileName=report.trx" /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
+          .\.sonar\scanner\dotnet-sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
+  # End analyze
